<?php
/*
 * This file is part of the ProductExternalLink plugin
 *
 *
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\ProductExternalLink\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Maker.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMakerRepository extends EntityRepository
{
}
